### ISSUE TITLE
User Stories, Context Diagram, Project Wiki

### ISSUE THREAD

**Issue by NigelLu** [gcivil-nyu-org/Wednesday-Fall2023-Team-2#1]
### Sprint 2 Checklist
- [x] Review project proposal and agree on project features as user stories
- [x] Identify the epics in our project
- [x] Create a high-level context analysis diagram and add to GitHub Wiki
- [x] Setup the frontend codebase and add to team repo
- [x] Prepare slides for sprint demo

Slides should include
- Explain how this Sprint has moved the team project forward.
- Explain: High Level Context Diagram, epics.
- Explain: User Stories within one epic.
- Explain: “Did the team achieve the Sprint goal?”
